
name: Remote Desktop Access
on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
      - name: Setup ngrok and remote desktop
        uses: actions/checkout@v2

      - name: Install ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ./ngrok tcp 3389

      - name: Open Remote Desktop Connection
        run: |
          mstsc /v:127.0.0.1:3389
